version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    platform: linux/amd64

  db:
    image: postgres:16
    env_file: .env
    restart: unless-stopped
    expose:
      - 5432

volumes:
  postgres_data:
