image:
  repository: your-registry/bot
  tag: latest
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  # Add your environment variables here
  # DATABASE_URL will come from a secret
  PYTHONUNBUFFERED: "1"

secrets:
  # Your sensitive environment variables
  DATABASE_URL: ""  # Will be base64 encoded
  # Add other secret env vars here 